<?php if ( ! defined( 'ABSPATH' ) ) { die; } // Cannot access pages directly.


    $fonts_old = array(
            "ABeeZee" => "ABeeZee",
            "Abel" => "Abel",
            "Abril Fatface" => "Abril+Fatface",
            "Aclonica" => "Aclonica",
            "Acme" => "Acme",
            "Actor" => "Actor",
            "Adamina" => "Adamina",
            "Advent Pro" => "Advent+Pro",
            "Aguafina Script" => "Aguafina+Script",
            "Akronim" => "Akronim",
            "Aladin" => "Aladin",
            "Aldrich" => "Aldrich",
            "Alegreya" => "Alegreya",
            "Alegreya SC" => "Alegreya+SC",
            "Alex Brush" => "Alex+Brush",
            "Alfa Slab One" => "Alfa+Slab+One",
            "Alice" => "Alice",
            "Alike" => "Alike",
            "Alike Angular" => "Alike+Angular",
            "Allan" => "Allan",
            "Allerta" => "Allerta",
            "Allerta Stencil" => "Allerta+Stencil",
            "Allura" => "Allura",
            "Almendra" => "Almendra",
            "Almendra Display" => "Almendra+Display",
            "Almendra SC" => "Almendra+SC",
            "Amarante" => "Amarante",
            "Amaranth" => "Amaranth",
            "Amatic SC" => "Amatic+SC",
            "Amethysta" => "Amethysta",
            "Anaheim" => "Anaheim",
            "Andada" => "Andada",
            "Andika" => "Andika",
            "Angkor" => "Angkor",
            "Annie Use Your Telescope" => "Annie+Use+Your+Telescope",
            "Anonymous Pro" => "Anonymous+Pro",
            "Antic" => "Antic",
            "Antic Didone" => "Antic+Didone",
            "Antic Slab" => "Antic+Slab",
            "Anton" => "Anton",
            "Arapey" => "Arapey",
            "Arbutus" => "Arbutus",
            "Arbutus Slab" => "Arbutus+Slab",
            "Architects Daughter" => "Architects+Daughter",
            "Archivo Black" => "Archivo+Black",
            "Archivo Narrow" => "Archivo+Narrow",
            "Arimo" => "Arimo",
            "Arizonia" => "Arizonia",
            "Armata" => "Armata",
            "Artifika" => "Artifika",
            "Arvo" => "Arvo",
            "Asap" => "Asap",
            "Asset" => "Asset",
            "Astloch" => "Astloch",
            "Asul" => "Asul",
            "Atomic Age" => "Atomic+Age",
            "Aubrey" => "Aubrey",
            "Audiowide" => "Audiowide",
            "Autour One" => "Autour+One",
            "Average" => "Average",
            "Average Sans" => "Average+Sans",
            "Averia Gruesa Libre" => "Averia+Gruesa+Libre",
            "Averia Libre" => "Averia+Libre",
            "Averia Sans Libre" => "Averia+Sans+Libre",
            "Averia Serif Libre" => "Averia+Serif+Libre",
            "Bad Script" => "Bad+Script",
            "Balthazar" => "Balthazar",
            "Bangers" => "Bangers",
            "Basic" => "Basic",
            "Battambang" => "Battambang",
            "Baumans" => "Baumans",
            "Bayon" => "Bayon",
            "Belgrano" => "Belgrano",
            "Belleza" => "Belleza",
            "BenchNine" => "BenchNine",
            "Bentham" => "Bentham",
            "Berkshire Swash" => "Berkshire+Swash",
            "Bevan" => "Bevan",
            "Bigelow Rules" => "Bigelow+Rules",
            "Bigshot One" => "Bigshot+One",
            "Bilbo" => "Bilbo",
            "Bilbo Swash Caps" => "Bilbo+Swash+Caps",
            "Bitter" => "Bitter",
            "Black Ops One" => "Black+Ops+One",
            "Bokor" => "Bokor",
            "Bonbon" => "Bonbon",
            "Boogaloo" => "Boogaloo",
            "Bowlby One" => "Bowlby+One",
            "Bowlby One SC" => "Bowlby+One+SC",
            "Brawler" => "Brawler",
            "Bree Serif" => "Bree+Serif",
            "Bubblegum Sans" => "Bubblegum+Sans",
            "Bubbler One" => "Bubbler+One",
            "Buda" => "Buda",
            "Buenard" => "Buenard",
            "Butcherman" => "Butcherman",
            "Butterfly Kids" => "Butterfly+Kids",
            "Cabin" => "Cabin",
            "Cabin Condensed" => "Cabin+Condensed",
            "Cabin Sketch" => "Cabin+Sketch",
            "Caesar Dressing" => "Caesar+Dressing",
            "Cagliostro" => "Cagliostro",
            "Calligraffitti" => "Calligraffitti",
            "Cambo" => "Cambo",
            "Candal" => "Candal",
            "Cantarell" => "Cantarell",
            "Cantata One" => "Cantata+One",
            "Cantora One" => "Cantora+One",
            "Capriola" => "Capriola",
            "Cardo" => "Cardo",
            "Carme" => "Carme",
            "Carrois Gothic" => "Carrois+Gothic",
            "Carrois Gothic SC" => "Carrois+Gothic+SC",
            "Carter One" => "Carter+One",
            "Caudex" => "Caudex",
            "Cedarville Cursive" => "Cedarville+Cursive",
            "Ceviche One" => "Ceviche+One",
            "Changa One" => "Changa+One",
            "Chango" => "Chango",
            "Chau Philomene One" => "Chau+Philomene+One",
            "Chela One" => "Chela+One",
            "Chelsea Market" => "Chelsea+Market",
            "Chenla" => "Chenla",
            "Cherry Cream Soda" => "Cherry+Cream+Soda",
            "Cherry Swash" => "Cherry+Swash",
            "Chewy" => "Chewy",
            "Chicle" => "Chicle",
            "Chivo" => "Chivo",
            "Cinzel" => "Cinzel",
            "Cinzel Decorative" => "Cinzel+Decorative",
            "Clicker Script" => "Clicker+Script",
            "Coda" => "Coda",
            "Coda Caption" => "Coda+Caption",
            "Codystar" => "Codystar",
            "Combo" => "Combo",
            "Comfortaa" => "Comfortaa",
            "Coming Soon" => "Coming+Soon",
            "Concert One" => "Concert+One",
            "Condiment" => "Condiment",
            "Content" => "Content",
            "Contrail One" => "Contrail+One",
            "Convergence" => "Convergence",
            "Cookie" => "Cookie",
            "Copse" => "Copse",
            "Corben" => "Corben",
            "Courgette" => "Courgette",
            "Cousine" => "Cousine",
            "Coustard" => "Coustard",
            "Covered By Your Grace" => "Covered+By+Your+Grace",
            "Crafty Girls" => "Crafty+Girls",
            "Creepster" => "Creepster",
            "Crete Round" => "Crete+Round",
            "Crimson Text" => "Crimson+Text",
            "Croissant One" => "Croissant+One",
            "Crushed" => "Crushed",
            "Cuprum" => "Cuprum",
            "Cutive" => "Cutive",
            "Cutive Mono" => "Cutive+Mono",
            "Damion" => "Damion",
            "Dancing Script" => "Dancing+Script",
            "Dangrek" => "Dangrek",
            "Dawning of a New Day" => "Dawning+of+a+New+Day",
            "Days One" => "Days+One",
            "Delius" => "Delius",
            "Delius Swash Caps" => "Delius+Swash+Caps",
            "Delius Unicase" => "Delius+Unicase",
            "Della Respira" => "Della+Respira",
            "Denk One" => "Denk+One",
            "Devonshire" => "Devonshire",
            "Didact Gothic" => "Didact+Gothic",
            "Diplomata" => "Diplomata",
            "Diplomata SC" => "Diplomata+SC",
            "Domine" => "Domine",
            "Donegal One" => "Donegal+One",
            "Doppio One" => "Doppio+One",
            "Dorsa" => "Dorsa",
            "Dosis" => "Dosis",
            "Dr Sugiyama" => "Dr+Sugiyama",
            "Droid Sans" => "Droid+Sans",
            "Droid Sans Mono" => "Droid+Sans+Mono",
            "Droid Serif" => "Droid+Serif",
            "Duru Sans" => "Duru+Sans",
            "Dynalight" => "Dynalight",
            "EB Garamond" => "EB+Garamond",
            "Eagle Lake" => "Eagle+Lake",
            "Eater" => "Eater",
            "Economica" => "Economica",
            "Electrolize" => "Electrolize",
            "Elsie" => "Elsie",
            "Elsie Swash Caps" => "Elsie+Swash+Caps",
            "Emblema One" => "Emblema+One",
            "Emilys Candy" => "Emilys+Candy",
            "Engagement" => "Engagement",
            "Englebert" => "Englebert",
            "Enriqueta" => "Enriqueta",
            "Erica One" => "Erica+One",
            "Esteban" => "Esteban",
            "Euphoria Script" => "Euphoria+Script",
            "Ewert" => "Ewert",
            "Exo" => "Exo",
            "Expletus Sans" => "Expletus+Sans",
            "Fanwood Text" => "Fanwood+Text",
            "Fascinate" => "Fascinate",
            "Fascinate Inline" => "Fascinate+Inline",
            "Faster One" => "Faster+One",
            "Fasthand" => "Fasthand",
            "Federant" => "Federant",
            "Federo" => "Federo",
            "Felipa" => "Felipa",
            "Fenix" => "Fenix",
            "Finger Paint" => "Finger+Paint",
            "Fjalla One" => "Fjalla+One",
            "Fjord One" => "Fjord+One",
            "Flamenco" => "Flamenco",
            "Flavors" => "Flavors",
            "Fondamento" => "Fondamento",
            "Fontdiner Swanky" => "Fontdiner+Swanky",
            "Forum" => "Forum",
            "Francois One" => "Francois+One",
            "Freckle Face" => "Freckle+Face",
            "Fredericka the Great" => "Fredericka+the+Great",
            "Fredoka One" => "Fredoka+One",
            "Freehand" => "Freehand",
            "Fresca" => "Fresca",
            "Frijole" => "Frijole",
            "Fruktur" => "Fruktur",
            "Fugaz One" => "Fugaz+One",
            "GFS Didot" => "GFS+Didot",
            "GFS Neohellenic" => "GFS+Neohellenic",
            "Gabriela" => "Gabriela",
            "Gafata" => "Gafata",
            "Galdeano" => "Galdeano",
            "Galindo" => "Galindo",
            "Gentium Basic" => "Gentium+Basic",
            "Gentium Book Basic" => "Gentium+Book+Basic",
            "Geo" => "Geo",
            "Geostar" => "Geostar",
            "Geostar Fill" => "Geostar+Fill",
            "Germania One" => "Germania+One",
            "Gilda Display" => "Gilda+Display",
            "Give You Glory" => "Give+You+Glory",
            "Glass Antiqua" => "Glass+Antiqua",
            "Glegoo" => "Glegoo",
            "Gloria Hallelujah" => "Gloria+Hallelujah",
            "Goblin One" => "Goblin+One",
            "Gochi Hand" => "Gochi+Hand",
            "Gorditas" => "Gorditas",
            "Goudy Bookletter 1911" => "Goudy+Bookletter+1911",
            "Graduate" => "Graduate",
            "Grand Hotel" => "Grand+Hotel",
            "Gravitas One" => "Gravitas+One",
            "Great Vibes" => "Great+Vibes",
            "Griffy" => "Griffy",
            "Gruppo" => "Gruppo",
            "Gudea" => "Gudea",
            "Habibi" => "Habibi",
            "Hammersmith One" => "Hammersmith+One",
            "Hanalei" => "Hanalei",
            "Hanalei Fill" => "Hanalei+Fill",
            "Handlee" => "Handlee",
            "Hanuman" => "Hanuman",
            "Happy Monkey" => "Happy+Monkey",
            "Headland One" => "Headland+One",
            "Henny Penny" => "Henny+Penny",
            "Herr Von Muellerhoff" => "Herr+Von+Muellerhoff",
            "Holtwood One SC" => "Holtwood+One+SC",
            "Homemade Apple" => "Homemade+Apple",
            "Homenaje" => "Homenaje",
            "IM Fell DW Pica" => "IM+Fell+DW+Pica",
            "IM Fell DW Pica SC" => "IM+Fell+DW+Pica+SC",
            "IM Fell Double Pica" => "IM+Fell+Double+Pica",
            "IM Fell Double Pica SC" => "IM+Fell+Double+Pica+SC",
            "IM Fell English" => "IM+Fell+English",
            "IM Fell English SC" => "IM+Fell+English+SC",
            "IM Fell French Canon" => "IM+Fell+French+Canon",
            "IM Fell French Canon SC" => "IM+Fell+French+Canon+SC",
            "IM Fell Great Primer" => "IM+Fell+Great+Primer",
            "IM Fell Great Primer SC" => "IM+Fell+Great+Primer+SC",
            "Iceberg" => "Iceberg",
            "Iceland" => "Iceland",
            "Imprima" => "Imprima",
            "Inconsolata" => "Inconsolata",
            "Inder" => "Inder",
            "Indie Flower" => "Indie+Flower",
            "Inika" => "Inika",
            "Irish Grover" => "Irish+Grover",
            "Istok Web" => "Istok+Web",
            "Italiana" => "Italiana",
            "Italianno" => "Italianno",
            "Jacques Francois" => "Jacques+Francois",
            "Jacques Francois Shadow" => "Jacques+Francois+Shadow",
            "Jim Nightshade" => "Jim+Nightshade",
            "Jockey One" => "Jockey+One",
            "Jolly Lodger" => "Jolly+Lodger",
            "Josefin Sans" => "Josefin+Sans",
            "Josefin Slab" => "Josefin+Slab",
            "Joti One" => "Joti+One",
            "Judson" => "Judson",
            "Julee" => "Julee",
            "Julius Sans One" => "Julius+Sans+One",
            "Junge" => "Junge",
            "Jura" => "Jura",
            "Just Another Hand" => "Just+Another+Hand",
            "Just Me Again Down Here" => "Just+Me+Again+Down+Here",
            "Kameron" => "Kameron",
            "Karla" => "Karla",
            "Kaushan Script" => "Kaushan+Script",
            "Kavoon" => "Kavoon",
            "Keania One" => "Keania+One",
            "Kelly Slab" => "Kelly+Slab",
            "Kenia" => "Kenia",
            "Khmer" => "Khmer",
            "Kite One" => "Kite+One",
            "Knewave" => "Knewave",
            "Kotta One" => "Kotta+One",
            "Koulen" => "Koulen",
            "Kranky" => "Kranky",
            "Kreon" => "Kreon",
            "Kristi" => "Kristi",
            "Krona One" => "Krona+One",
            "La Belle Aurore" => "La+Belle+Aurore",
            "Lancelot" => "Lancelot",
            "Lato" => "Lato",
            "League Script" => "League+Script",
            "Leckerli One" => "Leckerli+One",
            "Ledger" => "Ledger",
            "Lekton" => "Lekton",
            "Lemon" => "Lemon",
            "Libre Baskerville" => "Libre+Baskerville",
            "Life Savers" => "Life+Savers",
            "Lilita One" => "Lilita+One",
            "Limelight" => "Limelight",
            "Linden Hill" => "Linden+Hill",
            "Lobster" => "Lobster",
            "Lobster Two" => "Lobster+Two",
            "Londrina Outline" => "Londrina+Outline",
            "Londrina Shadow" => "Londrina+Shadow",
            "Londrina Sketch" => "Londrina+Sketch",
            "Londrina Solid" => "Londrina+Solid",
            "Lora" => "Lora",
            "Love Ya Like A Sister" => "Love+Ya+Like+A+Sister",
            "Loved by the King" => "Loved+by+the+King",
            "Lovers Quarrel" => "Lovers+Quarrel",
            "Luckiest Guy" => "Luckiest+Guy",
            "Lusitana" => "Lusitana",
            "Lustria" => "Lustria",
            "Macondo" => "Macondo",
            "Macondo Swash Caps" => "Macondo+Swash+Caps",
            "Magra" => "Magra",
            "Maiden Orange" => "Maiden+Orange",
            "Mako" => "Mako",
            "Marcellus" => "Marcellus",
            "Marcellus SC" => "Marcellus+SC",
            "Marck Script" => "Marck+Script",
            "Margarine" => "Margarine",
            "Marko One" => "Marko+One",
            "Marmelad" => "Marmelad",
            "Marvel" => "Marvel",
            "Mate" => "Mate",
            "Mate SC" => "Mate+SC",
            "Maven Pro" => "Maven+Pro",
            "McLaren" => "McLaren",
            "Meddon" => "Meddon",
            "MedievalSharp" => "MedievalSharp",
            "Medula One" => "Medula+One",
            "Megrim" => "Megrim",
            "Meie Script" => "Meie+Script",
            "Merienda" => "Merienda",
            "Merienda One" => "Merienda+One",
            "Merriweather" => "Merriweather",
            "Merriweather Sans" => "Merriweather+Sans",
            "Metal" => "Metal",
            "Metal Mania" => "Metal+Mania",
            "Metamorphous" => "Metamorphous",
            "Metrophobic" => "Metrophobic",
            "Michroma" => "Michroma",
            "Milonga" => "Milonga",
            "Miltonian" => "Miltonian",
            "Miltonian Tattoo" => "Miltonian+Tattoo",
            "Miniver" => "Miniver",
            "Miss Fajardose" => "Miss+Fajardose",
            "Modern Antiqua" => "Modern+Antiqua",
            "Molengo" => "Molengo",
            "Molle" => "Molle",
            "Monda" => "Monda",
            "Monofett" => "Monofett",
            "Monoton" => "Monoton",
            "Monsieur La Doulaise" => "Monsieur+La+Doulaise",
            "Montaga" => "Montaga",
            "Montez" => "Montez",
            "Montserrat" => "Montserrat",
            "Montserrat Alternates" => "Montserrat+Alternates",
            "Montserrat Subrayada" => "Montserrat+Subrayada",
            "Moul" => "Moul",
            "Moulpali" => "Moulpali",
            "Mountains of Christmas" => "Mountains+of+Christmas",
            "Mouse Memoirs" => "Mouse+Memoirs",
            "Mr Bedfort" => "Mr+Bedfort",
            "Mr Dafoe" => "Mr+Dafoe",
            "Mr De Haviland" => "Mr+De+Haviland",
            "Mrs Saint Delafield" => "Mrs+Saint+Delafield",
            "Mrs Sheppards" => "Mrs+Sheppards",
            "Muli" => "Muli",
            "Mystery Quest" => "Mystery+Quest",
            "Neucha" => "Neucha",
            "Neuton" => "Neuton",
            "New Rocker" => "New+Rocker",
            "News Cycle" => "News+Cycle",
            "Niconne" => "Niconne",
            "Nixie One" => "Nixie+One",
            "Nobile" => "Nobile",
            "Nokora" => "Nokora",
            "Norican" => "Norican",
            "Nosifer" => "Nosifer",
            "Nothing You Could Do" => "Nothing+You+Could+Do",
            "Noticia Text" => "Noticia+Text",
            "Nova Cut" => "Nova+Cut",
            "Nova Flat" => "Nova+Flat",
            "Nova Mono" => "Nova+Mono",
            "Nova Oval" => "Nova+Oval",
            "Nova Round" => "Nova+Round",
            "Nova Script" => "Nova+Script",
            "Nova Slim" => "Nova+Slim",
            "Nova Square" => "Nova+Square",
            "Numans" => "Numans",
            "Nunito" => "Nunito",
            "Odor Mean Chey" => "Odor+Mean+Chey",
            "Offside" => "Offside",
            "Old Standard TT" => "Old+Standard+TT",
            "Oldenburg" => "Oldenburg",
            "Oleo Script" => "Oleo+Script",
            "Oleo Script Swash Caps" => "Oleo+Script+Swash+Caps",
            "Open Sans" => "Open+Sans",
            "Open Sans Condensed" => "Open+Sans+Condensed",
            "Oranienbaum" => "Oranienbaum",
            "Orbitron" => "Orbitron",
            "Oregano" => "Oregano",
            "Orienta" => "Orienta",
            "Original Surfer" => "Original+Surfer",
            "Oswald" => "Oswald",
            "Over the Rainbow" => "Over+the+Rainbow",
            "Overlock" => "Overlock",
            "Overlock SC" => "Overlock+SC",
            "Ovo" => "Ovo",
            "Oxygen" => "Oxygen",
            "Oxygen Mono" => "Oxygen+Mono",
            "PT Mono" => "PT+Mono",
            "PT Sans" => "PT+Sans",
            "PT Sans Caption" => "PT+Sans+Caption",
            "PT Sans Narrow" => "PT+Sans+Narrow",
            "PT Serif" => "PT+Serif",
            "PT Serif Caption" => "PT+Serif+Caption",
            "Pacifico" => "Pacifico",
            "Paprika" => "Paprika",
            "Parisienne" => "Parisienne",
            "Passero One" => "Passero+One",
            "Passion One" => "Passion+One",
            "Patrick Hand" => "Patrick+Hand",
            "Patrick Hand SC" => "Patrick+Hand+SC",
            "Patua One" => "Patua+One",
            "Paytone One" => "Paytone+One",
            "Peralta" => "Peralta",
            "Permanent Marker" => "Permanent+Marker",
            "Petit Formal Script" => "Petit+Formal+Script",
            "Petrona" => "Petrona",
            "Philosopher" => "Philosopher",
            "Piedra" => "Piedra",
            "Pinyon Script" => "Pinyon+Script",
            "Pirata One" => "Pirata+One",
            "Plaster" => "Plaster",
            "Play" => "Play",
            "Playball" => "Playball",
            "Playfair Display" => "Playfair+Display",
            "Playfair Display SC" => "Playfair+Display+SC",
            "Podkova" => "Podkova",
            "Poiret One" => "Poiret+One",
            "Poller One" => "Poller+One",
            "Poly" => "Poly",
            "Pompiere" => "Pompiere",
            "Pontano Sans" => "Pontano+Sans",
            "Port Lligat Sans" => "Port+Lligat+Sans",
            "Port Lligat Slab" => "Port+Lligat+Slab",
            "Prata" => "Prata",
            "Preahvihear" => "Preahvihear",
            "Press Start 2P" => "Press+Start+2P",
            "Princess Sofia" => "Princess+Sofia",
            "Prociono" => "Prociono",
            "Prosto One" => "Prosto+One",
            "Puritan" => "Puritan",
            "Purple Purse" => "Purple+Purse",
            "Quando" => "Quando",
            "Quantico" => "Quantico",
            "Quattrocento" => "Quattrocento",
            "Quattrocento Sans" => "Quattrocento+Sans",
            "Questrial" => "Questrial",
            "Quicksand" => "Quicksand",
            "Quintessential" => "Quintessential",
            "Qwigley" => "Qwigley",
            "Racing Sans One" => "Racing+Sans+One",
            "Radley" => "Radley",
            "Raleway" => "Raleway",
            "Raleway Dots" => "Raleway+Dots",
            "Rambla" => "Rambla",
            "Rammetto One" => "Rammetto+One",
            "Ranchers" => "Ranchers",
            "Rancho" => "Rancho",
            "Rationale" => "Rationale",
            "Redressed" => "Redressed",
            "Reenie Beanie" => "Reenie+Beanie",
            "Revalia" => "Revalia",
            "Ribeye" => "Ribeye",
            "Ribeye Marrow" => "Ribeye+Marrow",
            "Righteous" => "Righteous",
            "Risque" => "Risque",
            "Roboto" => "Roboto",
            "Roboto Condensed" => "Roboto+Condensed",
            "Rochester" => "Rochester",
            "Rock Salt" => "Rock+Salt",
            "Rokkitt" => "Rokkitt",
            "Romanesco" => "Romanesco",
            "Ropa Sans" => "Ropa+Sans",
            "Rosario" => "Rosario",
            "Rosarivo" => "Rosarivo",
            "Rouge Script" => "Rouge+Script",
            "Ruda" => "Ruda",
            "Rufina" => "Rufina",
            "Ruge Boogie" => "Ruge+Boogie",
            "Ruluko" => "Ruluko",
            "Rum Raisin" => "Rum+Raisin",
            "Ruslan Display" => "Ruslan+Display",
            "Russo One" => "Russo+One",
            "Ruthie" => "Ruthie",
            "Rye" => "Rye",
            "Sacramento" => "Sacramento",
            "Sail" => "Sail",
            "Salsa" => "Salsa",
            "Sanchez" => "Sanchez",
            "Sancreek" => "Sancreek",
            "Sansita One" => "Sansita+One",
            "Sarina" => "Sarina",
            "Satisfy" => "Satisfy",
            "Scada" => "Scada",
            "Schoolbell" => "Schoolbell",
            "Seaweed Script" => "Seaweed+Script",
            "Sevillana" => "Sevillana",
            "Seymour One" => "Seymour+One",
            "Shadows Into Light" => "Shadows+Into+Light",
            "Shadows Into Light Two" => "Shadows+Into+Light+Two",
            "Shanti" => "Shanti",
            "Share" => "Share",
            "Share Tech" => "Share+Tech",
            "Share Tech Mono" => "Share+Tech+Mono",
            "Shojumaru" => "Shojumaru",
            "Short Stack" => "Short+Stack",
            "Siemreap" => "Siemreap",
            "Sigmar One" => "Sigmar+One",
            "Signika" => "Signika",
            "Signika Negative" => "Signika+Negative",
            "Simonetta" => "Simonetta",
            "Sintony" => "Sintony",
            "Sirin Stencil" => "Sirin+Stencil",
            "Six Caps" => "Six+Caps",
            "Skranji" => "Skranji",
            "Slackey" => "Slackey",
            "Smokum" => "Smokum",
            "Smythe" => "Smythe",
            "Sniglet" => "Sniglet",
            "Snippet" => "Snippet",
            "Snowburst One" => "Snowburst+One",
            "Sofadi One" => "Sofadi+One",
            "Sofia" => "Sofia",
            "Sonsie One" => "Sonsie+One",
            "Sorts Mill Goudy" => "Sorts+Mill+Goudy",
            "Source Code Pro" => "Source+Code+Pro",
            "Source Sans Pro" => "Source+Sans+Pro",
            "Special Elite" => "Special+Elite",
            "Spicy Rice" => "Spicy+Rice",
            "Spinnaker" => "Spinnaker",
            "Spirax" => "Spirax",
            "Squada One" => "Squada+One",
            "Stalemate" => "Stalemate",
            "Stalinist One" => "Stalinist+One",
            "Stardos Stencil" => "Stardos+Stencil",
            "Stint Ultra Condensed" => "Stint+Ultra+Condensed",
            "Stint Ultra Expanded" => "Stint+Ultra+Expanded",
            "Stoke" => "Stoke",
            "Strait" => "Strait",
            "Sue Ellen Francisco" => "Sue+Ellen+Francisco",
            "Sunshiney" => "Sunshiney",
            "Supermercado One" => "Supermercado+One",
            "Suwannaphum" => "Suwannaphum",
            "Swanky and Moo Moo" => "Swanky+and+Moo+Moo",
            "Syncopate" => "Syncopate",
            "Tangerine" => "Tangerine",
            "Taprom" => "Taprom",
            "Tauri" => "Tauri",
            "Telex" => "Telex",
            "Tenor Sans" => "Tenor+Sans",
            "Text Me One" => "Text+Me+One",
            "The Girl Next Door" => "The+Girl+Next+Door",
            "Tienne" => "Tienne",
            "Tinos" => "Tinos",
            "Titan One" => "Titan+One",
            "Titillium Web" => "Titillium+Web",
            "Trade Winds" => "Trade+Winds",
            "Trocchi" => "Trocchi",
            "Trochut" => "Trochut",
            "Trykker" => "Trykker",
            "Tulpen One" => "Tulpen+One",
            "Ubuntu" => "Ubuntu",
            "Ubuntu Condensed" => "Ubuntu+Condensed",
            "Ubuntu Mono" => "Ubuntu+Mono",
            "Ultra" => "Ultra",
            "Uncial Antiqua" => "Uncial+Antiqua",
            "Underdog" => "Underdog",
            "Unica One" => "Unica+One",
            "UnifrakturCook" => "UnifrakturCook",
            "UnifrakturMaguntia" => "UnifrakturMaguntia",
            "Unkempt" => "Unkempt",
            "Unlock" => "Unlock",
            "Unna" => "Unna",
            "VT323" => "VT323",
            "Vampiro One" => "Vampiro+One",
            "Varela" => "Varela",
            "Varela Round" => "Varela+Round",
            "Vast Shadow" => "Vast+Shadow",
            "Vibur" => "Vibur",
            "Vidaloka" => "Vidaloka",
            "Viga" => "Viga",
            "Voces" => "Voces",
            "Volkhov" => "Volkhov",
            "Vollkorn" => "Vollkorn",
            "Voltaire" => "Voltaire",
            "Waiting for the Sunrise" => "Waiting+for+the+Sunrise",
            "Wallpoet" => "Wallpoet",
            "Walter Turncoat" => "Walter+Turncoat",
            "Warnes" => "Warnes",
            "Wellfleet" => "Wellfleet",
            "Wendy One" => "Wendy+One",
            "Wire One" => "Wire+One",
            "Yanone Kaffeesatz" => "Yanone+Kaffeesatz",
            "Yellowtail" => "Yellowtail",
            "Yeseva One" => "Yeseva+One",
            "Yesteryear" => "Yesteryear",
            "Zeyada" => "Zeyada",
            );


    $fonts = array_flip($fonts_old); 


// ===============================================================================================
// -----------------------------------------------------------------------------------------------
// METABOX OPTIONS
// -----------------------------------------------------------------------------------------------
// ===============================================================================================

$options      = array();

// -----------------------------------------
// Page Metabox Options                    -
// -----------------------------------------
$options[]    = array(
  'id'        => 'hover_effects_options',
  'title'     => 'Hover Effects Options',
  'post_type' => 'hover_effect',
  'context'   => 'normal',
  'priority'  => 'default',
  'sections'  => array(




    // begin: a section
    array(
      'name'  => 'circle_section',
      //'title' => 'Circle Style',
      'icon'  => 'fa fa-cog',



      // begin: fields
      'fields' => array(
      
      
        array(
          'id'           => 'style',
          'type'         => 'image_select',
          'title'        => 'Select Style',
          'options'      => array(
            'circle'    => plugins_url( 'img/circle.png' , __FILE__ ),
            'square'    => plugins_url( 'img/square.png' , __FILE__ ),
            'square2'    => plugins_url( 'img/square2.png' , __FILE__ ),
            'caption'    => plugins_url( 'img/caption.png' , __FILE__ ),
          ),
          'default'      => 'circle'
        ), 
      
      
      
      

            array(
              'id'              => 'circle_option',
              'type'            => 'group',
              'title'           => '',
              'dependency'   => array( 'style_circle', '==', 'true' ),
              'button_title'    => 'Add New Hover Item',
              'accordion_title' => 'Hover Item',
              'fields'          => array(
              
                array(
                  'id'    => 'circle_image',
                  'type'  => 'image',
                  'title' => 'Hover Image',
                ),
                array(
                  'id'    => 'circle_title',
                  'type'  => 'text',
                  'title' => 'Title',
                  'default' => 'Heading Here',
                ),
                array(
                  'id'    => 'circle_desc',
                  'type'  => 'textarea',
                  'title' => 'Description',
                  'default' => 'description goes here',
                ),
                array(
                  'id'    => 'circle_link',
                  'type'  => 'text',
                  'title' => 'Image Link',
                  //'default' => '#',
                ),                                
                
              ),           
              
            ),


            array(
              'type'    => 'notice',
              'class'   => 'info',
              'content' => '<h4 align="center">Circle Style Settings are below</h4>',
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),


        // begin: settings field
                 
            array(
              'id'       => 'circle_effect',
              'type'     => 'select',
              'title'    => 'Select Effect',
              'dependency'   => array( 'style_circle', '==', 'true' ),
              'options'  => array(
                'effect1'  => 'Effect 1',
                'effect2'   => 'Effect 2',
                'effect3' => 'Effect 3',
                'effect4' => 'Effect 4',
                'effect5' => 'Effect 5',
                'effect6' => 'Effect 6',
                'effect7' => 'Effect 7',
                'effect8' => 'Effect 8',
                'effect9' => 'Effect 9',
                'effect10' => 'Effect 10',
                'effect11' => 'Effect 11',
                'effect12' => 'Effect 12',
                'effect13' => 'Effect 13',
                'effect14' => 'Effect 14',
                'effect15' => 'Effect 15',
                'effect16' => 'Effect 16',
                'effect17' => 'Effect 17',
                'effect18' => 'Effect 18',
                'effect19' => 'Effect 19',
                'effect20' => 'Effect 20',
              ),
              'default'  => 'effect1',
            ),


            array(
              'id'       => 'circle_animation',
              'type'     => 'select',
              'title'    => 'Animation Direction',
              'dependency'   => array( 'style_circle', '==', 'true' ),
              //'dependency'   => array( 'circle_effect', 'any', 'effect2' ),
              'options'  => array(
                'left_to_right'  => 'Left To Right',
                'right_to_left'   => 'Right To Left',
                'top_to_bottom' => 'Top To Bottom',
                'bottom_to_top' => 'Bottom To Top',
              ),
              'default'  => 'left_to_right',
            ),


            array(
              'id'      => 'circle_color',
              'type'    => 'color_picker',
              'title'   => 'Background Color',
              //'default' => 'rgba(33,71,224,0.5)',
              'rgba'    => true,
              'desc'    => 'use rgba color for transperant bg',
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),
            
            array(
              'id'      => 'circle_image_width',
              'type'    => 'number',
              'title'   => 'Image Size',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 216px',
              'default'  => '216',
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),
            
            array(
              'id'      => 'circle_column_space',
              'type'    => 'number',
              'title'   => 'Column Space',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'space between image column. default value is 15px',
              'default'  => '15',
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),

            array(
              'id'      => 'circle_row_space',
              'type'    => 'number',
              'title'   => 'Row Space',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'space between image row. default value is 26px',
              'default'  => '26',
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),
            
            array(
              'id'    => 'circle_border',
              'type'  => 'checkbox',
              'title' => 'Remove Border',
              //'label' => 'Remove Border'
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),
            
            

            array(
              'id'    => 'circle_underline',
              'type'  => 'checkbox',
              'title' => 'Remove Heading Underline',
              'options'    => array(
                'none'      => '',
              ),
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),
            
            array(
              'id'         => 'circle_link_open',
              'type'       => 'checkbox',
              'title'      => 'Open link in new Tab?',
              'options'    => array(
                '_blank'      => '',
              ),
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),

            array(
              'id'    => 'circle_position',
              'type'  => 'checkbox',
              'title' => 'Position',
              'label' => 'Center',             
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),
        
            array(
              'id'       => 'circle_font',
              'type'     => 'select',
              'title'    => 'Select Font',
              'dependency'   => array( 'style_circle', '==', 'true' ),
              'options'  => $fonts,
              'default'  => 'Open+Sans',
            ),
        
            array(
              'id'      => 'circle_heading_font_size',
              'type'    => 'number',
              'title'   => 'Heading Font Size',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 16px',
              'default'  => '16',
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),
                    
            array(
              'id'      => 'circle_heading_color',
              'type'    => 'color_picker',
              'title'   => 'Heading Color',
              'default' => '#fff',
              'desc'    => 'default color is #fff',
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),  
                  
            array(
              'id'      => 'circle_desc_font_size',
              'type'    => 'number',
              'title'   => 'Description Font Size',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 12px',
              'default'  => '12',
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),
            
            array(
              'id'      => 'circle_desc_color',
              'type'    => 'color_picker',
              'title'   => 'Description Color',
              'default' => '#fff',
              'desc'    => 'default color is #fff',
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ), 
            
            array(
              'id'      => 'circle_move_top',
              'type'    => 'number',
              'title'   => 'Move Texts Bottom',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'moving heading & desc texts to bottom. default value is 0px ',
              'default'  => '0',
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),            
            
            array(
              'id'    => 'circle_responsive',
              'type'  => 'checkbox',
              'title' => 'Responsive Options',
              'label' => 'enable',             
              'dependency'   => array( 'style_circle', '==', 'true' ),
            ),            
            
            /*
            array(
              'type'    => 'notice',
              'class'   => 'info',
              'content' => 'Mobile Responsive',
              'dependency'   => array( 'style_circle', '==', 'true' ),
              'dependency'   => array( 'circle_responsive', '==', 'true' ),
            ),
            */
            
            array(
              'id'      => 'circle_mobile_image_width',
              'type'    => 'number',
              'title'   => 'Mobile Image Size',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 240px',
              'default'  => '240',
              'dependency'   => array( 'style_circle', '==', 'true' ),
              'dependency'   => array( 'circle_responsive', '==', 'true' ),
            ),

            array(
              'id'      => 'circle_ipad_image_width',
              'type'    => 'number',
              'title'   => 'iPad Image Size',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 300px',
              'default'  => '300',
              'dependency'   => array( 'style_circle', '==', 'true' ),
              'dependency'   => array( 'circle_responsive', '==', 'true' ),
            ),





        // Square Feilds
    
            array(
               
              'id'              => 'square_option',
              'type'            => 'group',
              'title'           => '',
              'button_title'    => 'Add New Hover Item',
              'accordion_title' => 'Hover Item',
              'dependency'   => array( 'style_square', '==', 'true' ),
              'fields'          => array(
              
                array(
                  'id'    => 'square_image',
                  'type'  => 'image',
                  'title' => 'Hover Image',
                ),
                array(
                  'id'    => 'square_title',
                  'type'  => 'text',
                  'title' => 'Title',
                  'default' => 'Heading Here',
                ),
                array(
                  'id'    => 'square_desc',
                  'type'  => 'textarea',
                  'title' => 'Description',
                  'default' => 'description goes here',
                ),
                array(
                  'id'    => 'square_link',
                  'type'  => 'text',
                  'title' => 'Image Link',
                  //'default' => '#',
                ),                                
                
              ),         
              
            ),


            array(
              'type'    => 'notice',
              'class'   => 'info',
              'content' => '<h4 align="center">Square Style Settings are below</h4>',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),



        // begin: settings field
                
        
            array(
              'id'       => 'square_effect',
              'type'     => 'select',
              'title'    => 'Select Effect',
              'dependency'   => array( 'style_square', '==', 'true' ),
              'options'  => array(
                'effect1'  => 'Effect 1',
                'effect2'   => 'Effect 2',
                'effect3' => 'Effect 3',
                'effect4' => 'Effect 4',
                'effect5' => 'Effect 5',
                'effect6' => 'Effect 6',
                'effect7' => 'Effect 7',
                'effect8' => 'Effect 8',
                'effect9' => 'Effect 9',
                'effect10' => 'Effect 10',
                'effect11' => 'Effect 11',
                'effect12' => 'Effect 12',
                'effect13' => 'Effect 13',
                'effect14' => 'Effect 14',
                'effect15' => 'Effect 15',
              ),
              'default'  => 'effect1',
            ),


            array(
              'id'       => 'square_animation',
              'type'     => 'select',
              'title'    => 'Animation Direction',
              'options'  => array(
                'left_to_right'  => 'Left To Right',
                'right_to_left'   => 'Right To Left',
                'top_to_bottom' => 'Top To Bottom',
                'bottom_to_top' => 'Bottom To Top',
              ),
              'default'  => 'left_to_right',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),


            array(
              'id'      => 'square_color',
              'type'    => 'color_picker',
              'title'   => 'Background Color',
              //'default' => 'rgba(33,71,224,0.5)',
              'rgba'    => true,
              'desc'    => 'use rgba color for transperant bg',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),
            
            array(
              'id'      => 'square_image_width',
              'type'    => 'number',
              'title'   => 'Image Width',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 216px',
              'default'  => '216',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),

            array(
              'id'      => 'square_image_height',
              'type'    => 'number',
              'title'   => 'Image Height',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 216px',
              'default'  => '216',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),
            
            array(
              'id'      => 'square_column_space',
              'type'    => 'number',
              'title'   => 'Column Space',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'space between image column. default value is 15px',
              'default'  => '15',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),

            array(
              'id'      => 'square_row_space',
              'type'    => 'number',
              'title'   => 'Row Space',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'space between image row. default value is 26px',
              'default'  => '26',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),
            
            array(
              'id'         => 'square_link_open',
              'type'       => 'checkbox',
              'title'      => 'Open link in new Tab?',
              'options'    => array(
                '_blank'      => '',
              ),
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),

            array(
              'id'    => 'square_position',
              'type'  => 'checkbox',
              'title' => 'Position',
              'label' => 'Center',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),
        
            array(
              'id'       => 'square_font',
              'type'     => 'select',
              'title'    => 'Select Font',
              'dependency'   => array( 'style_square', '==', 'true' ),
              'options'  => $fonts,
              'default'  => 'Open+Sans',
            ),
        
            array(
              'id'      => 'square_heading_font_size',
              'type'    => 'number',
              'title'   => 'Heading Font Size',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 16px',
              'default'  => '16',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),
                    
            array(
              'id'      => 'square_heading_color',
              'type'    => 'color_picker',
              'title'   => 'Heading Color',
              'default' => '#fff',
              'desc'    => 'default color is #fff',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),  
                  
            array(
              'id'      => 'square_desc_font_size',
              'type'    => 'number',
              'title'   => 'Description Font Size',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 12px',
              'default'  => '12',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),
            
            array(
              'id'      => 'square_desc_color',
              'type'    => 'color_picker',
              'title'   => 'Description Color',
              'default' => '#fff',
              'desc'    => 'default color is #fff',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),             
            
            array(
              'id'      => 'square_move_texts',
              'type'    => 'number',
              'title'   => 'Move Texts',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'move texts to bottom. default value is 30px',
              'default'  => '30',
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),    
            
            
            array(
              'id'    => 'square_responsive',
              'type'  => 'checkbox',
              'title' => 'Responsive Options',
              'label' => 'enable',             
              'dependency'   => array( 'style_square', '==', 'true' ),
            ),            
            
            /*
            array(
              'type'    => 'notice',
              'class'   => 'info',
              'content' => 'Mobile Responsive',
              'dependency'   => array( 'style_circle', '==', 'true' ),
              'dependency'   => array( 'circle_responsive', '==', 'true' ),
            ),
            */
            
            array(
              'id'      => 'square_mobile_image_width',
              'type'    => 'number',
              'title'   => 'Mobile Image Width',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 240px',
              'default'  => '240',
              'dependency'   => array( 'style_square', '==', 'true' ),
              'dependency'   => array( 'square_responsive', '==', 'true' ),
            ),
            
            array(
              'id'      => 'square_mobile_image_height',
              'type'    => 'number',
              'title'   => 'Mobile Image Height',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 240px',
              'default'  => '240',
              'dependency'   => array( 'style_square', '==', 'true' ),
              'dependency'   => array( 'square_responsive', '==', 'true' ),
            ),
            
            array(
              'id'      => 'square_ipad_image_width',
              'type'    => 'number',
              'title'   => 'iPad Image Width',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 300px',
              'default'  => '300',
              'dependency'   => array( 'style_square', '==', 'true' ),
              'dependency'   => array( 'square_responsive', '==', 'true' ),
            ),
            
            array(
              'id'      => 'square_ipad_image_height',
              'type'    => 'number',
              'title'   => 'iPad Image Height',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 300px',
              'default'  => '300',
              'dependency'   => array( 'style_square', '==', 'true' ),
              'dependency'   => array( 'square_responsive', '==', 'true' ),
            ),            
            
            
            





        // Square 2 Feilds
    
            array(
               
              'id'              => 'square2_option',
              'type'            => 'group',
              'title'           => '',
              'button_title'    => 'Add New Hover Item',
              'accordion_title' => 'Hover Item',
              'dependency'   => array( 'style_square2', '==', 'true' ),
              'fields'          => array(
              
                array(
                  'id'    => 'square2_image',
                  'type'  => 'image',
                  'title' => 'Hover Image',
                ),
                array(
                  'id'    => 'square2_title',
                  'type'  => 'text',
                  'title' => 'Title',
                  'default' => 'Heading Here',
                ),
                array(
                  'id'    => 'square2_link',
                  'type'  => 'text',
                  'title' => 'Image Link',
                  //'default' => '#',
                ),                                
                
              ),         
              
            ),


            array(
              'type'    => 'notice',
              'class'   => 'info',
              'content' => '<h4 align="center">Square 2 Style Settings are below</h4>',
              'dependency'   => array( 'style_square2', '==', 'true' ),
            ),



        // begin: settings field
                
        
            array(
              'id'       => 'square2_effect',
              'type'     => 'select',
              'title'    => 'Select Effect',
              'dependency'   => array( 'style_square2', '==', 'true' ),
              'options'  => array(
                'effect1'  => 'Effect 1',
                'effect2'   => 'Effect 2',
                'effect3' => 'Effect 3',
                'effect4' => 'Effect 4',
                'effect5' => 'Effect 5',
                'effect6' => 'Effect 6',
                'effect7' => 'Effect 7',
                'effect8' => 'Effect 8',
                'effect9' => 'Effect 9',
                'effect10' => 'Effect 10',
                'effect11' => 'Effect 11',
                'effect12' => 'Effect 12',
                'effect13' => 'Effect 13',
                'effect14' => 'Effect 14',
                'effect15' => 'Effect 15',
                'effect16' => 'Effect 16',
                'effect17' => 'Effect 17',
                'effect18' => 'Effect 18',
                'effect19' => 'Effect 19',
                'effect20' => 'Effect 20',
              ),
              'default'  => 'effect1',
            ),
            
            array(
              'id'      => 'square2_image_width',
              'type'    => 'number',
              'title'   => 'Image Width',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 216px',
              'default'  => '216',
              'dependency'   => array( 'style_square2', '==', 'true' ),
            ),

            array(
              'id'      => 'square2_image_height',
              'type'    => 'number',
              'title'   => 'Image Height',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 216px',
              'default'  => '216',
              'dependency'   => array( 'style_square2', '==', 'true' ),
            ),
            
            array(
              'id'      => 'square2_column_space',
              'type'    => 'number',
              'title'   => 'Column Space',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'space between image column. default value is 15px',
              'default'  => '15',
              'dependency'   => array( 'style_square2', '==', 'true' ),
            ),

            array(
              'id'      => 'square2_row_space',
              'type'    => 'number',
              'title'   => 'Row Space',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'space between image row. default value is 26px',
              'default'  => '26',
              'dependency'   => array( 'style_square2', '==', 'true' ),
            ),
            
            array(
              'id'         => 'square2_link_open',
              'type'       => 'checkbox',
              'title'      => 'Open link in new Tab?',
              'options'    => array(
                '_blank'      => '',
              ),
              'dependency'   => array( 'style_square2', '==', 'true' ),
            ),

            array(
              'id'    => 'square2_position',
              'type'  => 'checkbox',
              'title' => 'Position',
              'label' => 'Center',
              'dependency'   => array( 'style_square2', '==', 'true' ),
            ),
        
            array(
              'id'       => 'square2_font',
              'type'     => 'select',
              'title'    => 'Select Font',
              'dependency'   => array( 'style_square2', '==', 'true' ),
              'options'  => $fonts,
              'default'  => 'Open+Sans',
            ),
        
            array(
              'id'      => 'square2_heading_font_size',
              'type'    => 'number',
              'title'   => 'Heading Font Size',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 16px',
              'default'  => '16',
              'dependency'   => array( 'style_square2', '==', 'true' ),
            ),
                                        
            array(
              'id'      => 'square2_move_texts',
              'type'    => 'number',
              'title'   => 'Move Texts Top/Bottom',
              'after'   => '<i class="cs-text-muted">(%)</i>',
              'desc'    => 'move texts to bottom & top. default value is 50%',
              'default'  => '50',
              'dependency'   => array( 'style_square2', '==', 'true' ),
            ),    
            
            
            array(
              'id'    => 'square2_responsive',
              'type'  => 'checkbox',
              'title' => 'Responsive Options',
              'label' => 'enable',             
              'dependency'   => array( 'style_square2', '==', 'true' ),
            ),            
            
            /*
            array(
              'type'    => 'notice',
              'class'   => 'info',
              'content' => 'Mobile Responsive',
              'dependency'   => array( 'style_circle', '==', 'true' ),
              'dependency'   => array( 'circle_responsive', '==', 'true' ),
            ),
            */
            
            array(
              'id'      => 'square2_mobile_image_width',
              'type'    => 'number',
              'title'   => 'Mobile Image Width',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 240px',
              'default'  => '240',
              'dependency'   => array( 'style_square2', '==', 'true' ),
              'dependency'   => array( 'square2_responsive', '==', 'true' ),
            ),
            
            array(
              'id'      => 'square2_mobile_image_height',
              'type'    => 'number',
              'title'   => 'Mobile Image Height',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 240px',
              'default'  => '240',
              'dependency'   => array( 'style_square2', '==', 'true' ),
              'dependency'   => array( 'square2_responsive', '==', 'true' ),
            ),
            
            array(
              'id'      => 'square2_ipad_image_width',
              'type'    => 'number',
              'title'   => 'iPad Image Width',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 300px',
              'default'  => '300',
              'dependency'   => array( 'style_square2', '==', 'true' ),
              'dependency'   => array( 'square2_responsive', '==', 'true' ),
            ),
            
            array(
              'id'      => 'square2_ipad_image_height',
              'type'    => 'number',
              'title'   => 'iPad Image Height',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 300px',
              'default'  => '300',
              'dependency'   => array( 'style_square2', '==', 'true' ),
              'dependency'   => array( 'square2_responsive', '==', 'true' ),
            ),







            // start: Caption fields
            
            array(
              'id'              => 'caption_option',
              'type'            => 'group',
              'title'           => '',
              'dependency'   => array( 'style_caption', '==', 'true' ),
              'button_title'    => 'Add New Hover Item',
              'accordion_title' => 'Hover Item',
              'fields'          => array(
              
                array(
                  'id'    => 'caption_image',
                  'type'  => 'image',
                  'title' => 'Hover Image',
                ),
                array(
                  'id'    => 'caption_title',
                  'type'  => 'text',
                  'title' => 'Title',
                  'default' => 'Heading Here',
                ),
                array(
                  'id'    => 'caption_desc',
                  'type'  => 'textarea',
                  'title' => 'Description',
                  'default' => 'description goes here',
                ),
                array(
                  'id'    => 'caption_link',
                  'type'  => 'text',
                  'title' => 'Image Link',
                  //'default' => '#',
                ),                                
                
              ),           
              
            ),


            array(
              'type'    => 'notice',
              'class'   => 'info',
              'content' => '<h4 align="center">Caption Style Settings are below</h4>',
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),
            
                        
        // begin: settings field
                
        
            array(
              'id'       => 'caption_effect',
              'type'     => 'select',
              'title'    => 'Select Effect',
              'dependency'   => array( 'style_caption', '==', 'true' ),
              'options'  => array(
                'effect1'  => 'Effect 1',
                'effect2'   => 'Effect 2',
                'effect3' => 'Effect 3',
                'effect4' => 'Effect 4',
                'effect5' => 'Effect 5',
                'effect6' => 'Effect 6',
                'effect7' => 'Effect 7',
                'effect8' => 'Effect 8',
                'effect9' => 'Effect 9',
                'effect10' => 'Effect 10',
                'effect11' => 'Effect 11',
                'effect12' => 'Effect 12',
                'effect13' => 'Effect 13',
                'effect14' => 'Effect 14',
                'effect15' => 'Effect 15',
                'effect16' => 'Effect 16',
                'effect17' => 'Effect 17',
                'effect18' => 'Effect 18',
                'effect19' => 'Effect 19',
                'effect20' => 'Effect 20',
              ),
              'default'  => 'effect1',
            ), 


            array(
              'id'      => 'caption_image_width',
              'type'    => 'number',
              'title'   => 'Image Width',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 216px',
              'default'  => '216',
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),

            array(
              'id'      => 'caption_image_height',
              'type'    => 'number',
              'title'   => 'Image Height',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 216px',
              'default'  => '216',
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),
            
            array(
              'id'      => 'caption_color',
              'type'    => 'color_picker',
              'title'   => 'Background Color',
              //'default' => 'rgba(33,71,224,0.5)',
              'rgba'    => true,
              'desc'    => 'use rgba color for transperant bg',
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),
            
            array(
              'id'      => 'caption_column_space',
              'type'    => 'number',
              'title'   => 'Column Space',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'space between image column. default value is 15px',
              'default'  => '15',
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),

            array(
              'id'      => 'caption_row_space',
              'type'    => 'number',
              'title'   => 'Row Space',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'space between image row. default value is 26px',
              'default'  => '26',
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),
            
            array(
              'id'    => 'caption_border',
              'type'  => 'checkbox',
              'title' => 'Remove Border',
              //'label' => 'Remove Border'
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),
                        
            array(
              'id'         => 'caption_link_open',
              'type'       => 'checkbox',
              'title'      => 'Open link in new Tab?',
              'options'    => array(
                '_blank'      => '',
              ),
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),

            array(
              'id'    => 'caption_position',
              'type'  => 'checkbox',
              'title' => 'Position',
              'label' => 'Center',
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),
        
            array(
              'id'       => 'caption_font',
              'type'     => 'select',
              'title'    => 'Select Font',
              'dependency'   => array( 'style_caption', '==', 'true' ),
              'options'  => $fonts,
              'default'  => 'Open+Sans',
            ),
        
            array(
              'id'      => 'caption_heading_font_size',
              'type'    => 'number',
              'title'   => 'Heading Font Size',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 16px',
              'default'  => '16',
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),
            
            array(
              'id'      => 'caption_heading_color',
              'type'    => 'color_picker',
              'title'   => 'Heading Color',
              'default' => '#fff',
              'desc'    => 'default color is #fff',
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),  
                  
            array(
              'id'      => 'caption_desc_font_size',
              'type'    => 'number',
              'title'   => 'Description Font Size',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 12px',
              'default'  => '12',
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),
            
            array(
              'id'      => 'caption_desc_color',
              'type'    => 'color_picker',
              'title'   => 'Description Color',
              'default' => '#fff',
              'desc'    => 'default color is #fff',
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),                                         
                       
            array(
              'id'    => 'caption_responsive',
              'type'  => 'checkbox',
              'title' => 'Responsive Options',
              'label' => 'enable',             
              'dependency'   => array( 'style_caption', '==', 'true' ),
            ),            
            
            /*
            array(
              'type'    => 'notice',
              'class'   => 'info',
              'content' => 'Mobile Responsive',
              'dependency'   => array( 'style_circle', '==', 'true' ),
              'dependency'   => array( 'circle_responsive', '==', 'true' ),
            ),
            */
            
            array(
              'id'      => 'caption_mobile_image_width',
              'type'    => 'number',
              'title'   => 'Mobile Image Width',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 240px',
              'default'  => '240',
              'dependency'   => array( 'style_caption', '==', 'true' ),
              'dependency'   => array( 'caption_responsive', '==', 'true' ),
            ),
            
            array(
              'id'      => 'caption_mobile_image_height',
              'type'    => 'number',
              'title'   => 'Mobile Image Height',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 240px',
              'default'  => '240',
              'dependency'   => array( 'style_caption', '==', 'true' ),
              'dependency'   => array( 'caption_responsive', '==', 'true' ),
            ),
            
            array(
              'id'      => 'caption_ipad_image_width',
              'type'    => 'number',
              'title'   => 'iPad Image Width',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 300px',
              'default'  => '300',
              'dependency'   => array( 'style_caption', '==', 'true' ),
              'dependency'   => array( 'caption_responsive', '==', 'true' ),
            ),
            
            array(
              'id'      => 'caption_ipad_image_height',
              'type'    => 'number',
              'title'   => 'iPad Image Height',
              'after'   => '<i class="cs-text-muted">(px)</i>',
              'desc'    => 'default value is 300px',
              'default'  => '300',
              'dependency'   => array( 'style_caption', '==', 'true' ),
              'dependency'   => array( 'caption_responsive', '==', 'true' ),
            ),

                             
        
      ), // end: fields
      
), // end: a section





    // end: a section

  ),
);




CSFramework_Metabox::instance( $options );
